# 관리자 권한
sudo: required

# 언어(플랫폼) 선택
language: generic

# 도커 환경 구성
services:
  - docker

# 스크립트를 실행할 수 있는 환경(스크립트 이전에 해야할 일)
before_install:
# 에코로 출력하는 부분
  - echo "start creating an image with dockerfile"
# 진짜 이미지를 빌드하는 부분 
  - docker build -t gaeun1116/react-docker:latest-f Dockerfile.dev .

# 실행할 스크립트(테스트 실행)
script:
  - docker run -e CI=true gaeun1116/react-docker:latest npm run test -- --coverage
# 테스트는 이미지를 이용해서 컨테이너를 실행하고 CI=true는 에러 해결 위해서 --coverage 테스트를 상세하게 볼 수 있게

# 테스트 성공 후 할 일
after_success:
  - echo "Test success"